import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "Scape Sync",
  description: "Generated by Scape Sync app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="public-sans">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
